config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'tasks/create'

  match 'accounts/tasks/new_ad_unit_field', to: 'tasks#new_ad_unit_field', via: :post
  match 'accounts/tasks/start', to: 'tasks#start_sync_with_sidekiq', via: :post
  match 'tasks/test', to: 'tasks#test', via: :get
  match 'accounts/tasks/get_tasks_status', to: 'tasks#get_tasks_status', via: :get
  
  # match 'api/tasks/update_status', to: 'api/local/tasks#get_status_from_sidekiq', via: :get

  namespace :api do
    namespace :local do
      match '/update_status', to: 'tasks#update_status_from_sidekiq', via: :patch
    end
  end
  get 'account_apps/create'

  get 'adunit_links/create'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  root 'accounts#index'

  resources :accounts do
    resources :adunits
    resources :account_apps
  end
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :adunits, dependent: :destroy
  has_many :account_apps, dependent: :destroy
  has_many :task, dependent: :destroy
end

app/models/account_app.rb
class AccountApp < ApplicationRecord
  belongs_to :account
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/adunit.rb
class Adunit < ApplicationRecord
  belongs_to :account
  has_many :adunit_links
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  
  belongs_to :account
  serialize(:names, Array)
end

app/controllers/account_apps_controller.rb
class AccountAppsController < ApplicationController
  def create
    @account = Account.find(params[:account_id])
    @app = @account.account_apps.create(app_params)
    redirect_to account_path(@account)
  end

  private 

  def app_params
    params[:app].permit(:description, :link)    
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts}
      format.json { render :json => @accounts}
    end
  end

  def new    
  end

  def create
    @account = Account.new(account_params)
    @account.save
    redirect_to @account
  end

  def update
    @account = Account.find(params[:id])

    if @account.update(account_params)
      redirect_to @account
    else
      render 'edit'
    end
  end

  def show
    @account = Account.find(params[:id])
  end

  def edit
    @account = Account.find(params[:id])
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_path
    
  end

  private

  def account_params
    params[:account].permit(:login,:password)    
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
    
  end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/adunits_controller.rb
class AdunitsController < ApplicationController


  def new    
  end

  def create
    @account = Account.find(params[:account_id])
    @adunit = @account.adunits.create(adunit_params)
    redirect_to account_path(@account)
    # render plain: @account.inspect   
  end

  def update
    @adunit = Adunit.find(params[:id])

    if @adunit.update(adunit_params)
      redirect_to @adunit.account
    else
      render 'edit'
    end
  end


  def edit

    @adunit = Adunit.find(params[:id])
    # render plain: params.inspect
  end



  private

  def adunit_params
    params[:adunit].permit(:name)    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # skip_before_action :authenticate_admin!, only: [:update_status_from_sidekiq]

  def test
    redirect_to "http://google.ru"
  end
  
  def create

    @account = Account.find(params[:task][:account_id])
    @app = @account.account_apps.find_by_description(params[:task][:app])
    params[:task][:link] = @app.link
    params[:task][:status] = "не обработано"
    my_array_for_names = []
    params[:task][:names].each do |name|
      name = {name: name}
      my_array_for_names << name
    end
    params[:task][:names] = my_array_for_names
    @task = @account.task.new(task_params)

    @task.save
    redirect_to account_path(@account)
    # render plain: params[:task].inspect
  end

  # /tasks/new_ad_unit_field
  def new_ad_unit_field
    @account = Account.find(params[:account_id])
    @ad_unit = @account.adunits.all
    render json: @ad_unit
  end

  def get_tasks_status
    @account = Account.find(params[:account_id])
    tasks = @account.task.all
    render json: tasks.to_json
  end

  def start_sync_with_sidekiq
    # flash[:notice] = "Successfully created..."
    @account = Account.find(params[:account_id])
    account_id = params[:account_id]
    @tasks = @account.task.where(status: "не обработано")
    message_success = {message: "Окей понеслась"}
    message_notice = { message: "нет задач для обработки"}
    tasks = @tasks
    if tasks.size > 0
      HardWorker.perform_async(account_id)
      render json: message_success.to_json
    else
      render json: message_notice.to_json
    end
    # HardWorker.new.perform(account_id)
    # render json: @tasks
  end

  private
  def task_params
    params.require(:task).permit(:app, :link, :status, names: [:name])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end
end

app/helpers/account_apps_helper.rb
module AccountAppsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/adunits_helper.rb
module AdunitsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/account_apps/create.html.erb
<h1>AccountApps#create</h1>
<p>Find me in app/views/account_apps/create.html.erb</p>

app/views/accounts/_nav.html.erb
<div class="container">
  <div class="nav navbar-nav">
    <li><%= link_to "Add account", new_account_path %></li>
    <li><%= link_to "All accounts", accounts_path, method: :get %></li>
    <li><%= link_to '' %></li>
    <li><%= link_to '' %></li>
    <li><%= link_to '' %></li>
  </div>
  
</div>

app/views/accounts/edit.html.erb
<div class="container">
  <%= render partial: "nav" %>
  <div class="admin-form-login">
    <%= form_for(@account) do |f| %>
      <div class="form-group">
        <%= f.label :login, "Login"  %>
        <%= f.text_field :login, placeholder: "please enter login for new acc", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password"  %>
        <%= f.text_field :password, placeholder: "please enter password for new acc", class: "form-control" %>
      </div>
      <div class="form-group">
        <%=  f.submit "Submit", :disable_with => 'Submiting', class: "btn" %> 
      </div>
    <% end %>
  </div>

</div>

app/views/accounts/index.html.erb
<div class="container">
  <div class="account-panel">
    <%= render partial: 'nav' %>
    
  </div>
  

  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Panel All account</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>#id</th>
          <th>login</th>
          <th>add task for my target</th>
        </tr>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= account.id %></td>
            <td><%=  link_to account.login, account_path(account.id) %></td>
            <td><%= link_to("sync", accounts_tasks_start_path(account_id: account.id, params2: "test2"),remote: true, method: :post ) %> 
            </td>
            <td><span data-popup-account-id="<%= account.id %>" data-mfp-src="#popup-tasks" class="btn js-popup" style="border: 1px solid #000;">статусы задач</span></td>
            <td><%= link_to "Edit", edit_account_path(account.id) %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>
  </div>
</div>

<section class="popup">
  <div id="popup-tasks" data-popup-id="" class="mfp-hide main-popup">
    <h2>account: <span class="popup_tasks_account_name"></span> </h2>
    <table class="table">
      <thead>
        <tr>
          <th>tasks</th>
          <th>status</th>
        </tr>
      </thead>
      <tbody class="table_for_tasks">
        
      </tbody>
    </table>
    <button class="popup_tasks_update-btn btn">update</button>
  </div>
</section>


<script>
$(document).ready(function(){
  var popup_account_id;
  $("span[data-popup-account-id]").on('click', function(e){
    e.preventDefault();
    popup_account_id = $(this).attr('data-popup-account-id');
    var table_for_tasks = $(".table_for_tasks");
    table_for_tasks.find('tr').remove();
    var popup_tasks_account_name = $(".popup_tasks_account_name");
    popup_tasks_account_name.text(popup_account_id);
    console.log(popup_account_id);
  });
  $(".popup_tasks_update-btn").on('click', function(e){
    
    e.preventDefault();
    $.ajax({
      url: '/accounts/tasks/get_tasks_status',
      type: 'GET',
      data: {account_id: popup_account_id},
      success: function(data) {
        console.log(data);
        var table_for_tasks = $(".table_for_tasks");
        var row_task;
        table_for_tasks.find('tr').remove();
        $.each(data, function(key, task){
          row_task = $('<tr><td>' + task.app + '</td><td>' + task.status + '</td></tr>')
          .appendTo(table_for_tasks);
        });        
      }
    });
  });
});
</script>

app/views/accounts/new.html.erb
<div class="container">
  <%= render partial: 'nav' %>
  <h2>Add new account</h2>
  <div class="admin-form-login">
    <%=  form_for :account, url: accounts_path do |f| %>
    <div class="form-group">
      <%= f.label :login, "Login"  %>
      <%= f.text_field :login, placeholder: "please enter login for new acc", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password, "Password"  %>
      <%= f.text_field :password, placeholder: "please enter password for new acc", class: "form-control" %>
    </div>
    <div class="form-group">
      <%=  f.submit "Submit", :disable_with => 'Submiting...', class: "btn" %> 
    </div>
    <% end %> 
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <%= render partial: 'nav' %>
  <h2>account with id: <%= @account.id %></h2>
  <p>login: <%= @account.login %></p>
  <p>password: <%= @account.password %></p>
  <p><%= link_to "Edit", edit_account_path(@account.id) %></p>
  <p><%= link_to "Delete account", account_path(@account.id), method: :delete, data: {confirm: "Are you sure"} %></p>
  <button data-mfp-src="#test" class="js-popup btn">create new task</button>
  <button data-mfp-src="#tasksList" class="js-popup btn btn-warning">all tasks list</button>
</div>

<div class="container">
  
  <h2>New adunit</h2>
  <div class="admin-form-login">
    <%= form_for(:adunit, url: account_adunits_path(@account.id)) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, "name"  %>
        <%= f.text_field :name, placeholder: "", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%=  f.submit "Submit", class: "btn" %> 
      </div>
    <% end %>
  </div>

</div>

<div class="container">
  
  <h2>New app</h2>
  <div class="admin-form-login">
    <%= form_for(:app, url: account_account_apps_path(@account.id)) do |f| %>
      <div class="form-group">
        <%= f.label :description, "Description"  %>
        <%= f.text_field :description, placeholder: "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :link, "link"  %>
        <%= f.text_field :link, placeholder: "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%=  f.submit "Submit", class: "btn" %> 
      </div>
    <% end %>
  </div>

</div>

<div class="container">
  <h2>My apps</h2>
  <% @account.account_apps.each do |app| %>
    <ul>
      <li><%= app.id %></li>
      <li><%= app.description %></li>
      <li><%= app.link %></li>
    </ul>
  <% end %>  
  
</div>
<div class="container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Panel adunits</div>
    <!-- Table -->
    <table class="table">
      <thead>
        <tr>
          <th>#id</th>
          <th>name</th>          
        </tr>
      </thead>
      <tbody>
        <% @account.adunits.each do |adunit| %>
          <tr>
            <td><%= adunit.id %></td>            
            <td><%= adunit.name %></td>            
            <td><%= link_to "Edit", edit_account_adunit_path(@account.id,adunit.id) %></td>
          </tr>
        <% end %>
        
      </tbody>
    </table>
  </div>
</div>

<div class="popup"> 
  <div id="tasksList" class="mfp-hide main-popup">
    <h3>all tasks</h3>
    <% @account.task.each do |task| %>
    <div style="border: 1px solid #000;">
      <p>id: <%= task.id %></p>
      <p>status: <%= task.status %></p>
      <p><%= task.app %></p>
    </div>
    <% end %>
  </div>

  <div id="test" class="mfp-hide main-popup">
    <h3 class="popup-title">test</h3>
    
    <%= form_for(:task, url: tasks_create_path, html: {class: "popup-form"}, method: :get ) do |f| %>
      <div class="form-group">        
        <%= f.hidden_field( :account_id, value: "#{@account.id}" )%>

        <label for="" class="">Choose app</label>
        <%= f.select(:app, @account.account_apps.collect do |option|
          [option.description]          
        end,{}, {class: "form-control"}) %>

        
      </div>
      <div class="form-group">
        <label for="" class="">pad name</label>
        
      </div>
      <div class="form-group">
        

      </div>
      <div class="form-group">
        <%= button_tag( "Add additional pad name", {id: "testButton", data: {account_id: "#{@account.id}"}} ) %>       
      </div>
      <div id="extraFields" class="form-group">
        
      </div>
      
      <div class="form-group">
        <%=  f.submit "Submit", class: "btn" %> 
      </div>
    <% end %>
    
  </div>
</div>

app/views/adunits/edit.html.erb
<div class="container">

  <div class="admin-form-login">
    <%= form_for(@adunit, url: account_adunit_path(@adunit.id), method: :patch) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, "name"  %>
        <%= f.text_field :name, placeholder: "please enter name for new adunit", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%=  f.submit "Submit", :disable_with => 'Submiting', class: "btn" %> 
      </div>
    <% end %>
  </div>

</div>